import { useEffect, useState } from 'react'
import { api } from '../../api/client.js'
import { LoadingPage, EmptyState } from '../../components/ui/Feedback.jsx'
import StatusBadge from '../../components/ui/StatusBadge.jsx'
import { MONTHS } from '../../utils/format.js'
import { openFile } from '../../utils/files.js'

export default function WorkerSalary() {
  const now = new Date()
  const [month, setMonth] = useState(now.getMonth() + 1)
  const [year, setYear] = useState(now.getFullYear())
  const [data, setData] = useState(null)
  const [history, setHistory] = useState(null)

  useEffect(() => {
    setData(null)
    api.get('/salary/mine', { year, month }).then((res) => setData(res.data)).catch(() => setData(null))
  }, [month, year])

  useEffect(() => {
    setHistory(null)
    const months = []
    for (let i = 0; i < 6; i++) {
      const d = new Date()
      d.setMonth(d.getMonth() - i)
      months.push({ year: d.getFullYear(), month: d.getMonth() + 1 })
    }
    Promise.all(months.map((m) => api.get('/salary/mine', m).then((res) => res.data).catch(() => null)))
      .then((rows) => setHistory(rows.filter(Boolean)))
  }, [])

  if (history === null) return <LoadingPage label="Loading salary..." />

  if (!data) {
    return (
      <div>
        <div className="page-header">
          <div>
            <div className="page-title">My Salary</div>
            <div className="page-subtitle">Monthly payroll details and salary slips</div>
          </div>
        </div>
        <EmptyState
          icon="💰"
          title="No salary record yet"
          sub="Your payroll for this month has not been calculated yet. Contact the HR / IT Department if you expected it."
        />
      </div>
    )
  }

  const openSlip = (id) => {
    openFile(`/salary/${id}/slip`)
  }

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title">My Salary</div>
          <div className="page-subtitle">Monthly payroll details and salary slips</div>
        </div>
        <div className="flex items-center gap-8">
          <select className="input" style={{ width: 150 }} value={month} onChange={(e) => setMonth(Number(e.target.value))}>
            {MONTHS.map((m, i) => <option key={i} value={i + 1}>{m}</option>)}
          </select>
          <select className="input" style={{ width: 110 }} value={year} onChange={(e) => setYear(Number(e.target.value))}>
            {[now.getFullYear(), now.getFullYear() - 1].map((y) => <option key={y} value={y}>{y}</option>)}
          </select>
        </div>
      </div>

      <div className="grid grid-2">
        <div className="card">
          <div className="card-header">
            <div className="card-title">Payslip Summary — {MONTHS[month - 1]} {year}</div>
            <StatusBadge status={data.status} labels={{ draft: 'Draft', finalized: 'Finalized', paid: 'Paid' }} />
          </div>
          <div className="card-body">
            <table className="summary-table">
              <tbody>
                <tr><td>Basic Salary</td><td>₹ {Number(data.basicSalary).toLocaleString('en-IN')}</td></tr>
                <tr><td>HRA</td><td>₹ {Number(data.hra).toLocaleString('en-IN')}</td></tr>
                <tr><td>Other Allowances</td><td>₹ {Number(data.otherAllowances).toLocaleString('en-IN')}</td></tr>
                <tr className="total"><td>Gross Salary</td><td>₹ {Number(data.grossSalary).toLocaleString('en-IN')}</td></tr>
                <tr><td>Present Days</td><td>{data.presentDays}</td></tr>
                <tr><td>Leave Days</td><td>{data.leaveDays}</td></tr>
                <tr><td>Absent Days</td><td>{data.absentDays}</td></tr>
                <tr><td>LOP Days</td><td>{data.lopDays}</td></tr>
                <tr><td>Total Deductions</td><td>₹ {Number(data.totalDeductions).toLocaleString('en-IN')}</td></tr>
                <tr className="total"><td>Net Salary</td><td>₹ {Number(data.netSalary).toLocaleString('en-IN')}</td></tr>
              </tbody>
            </table>
            {data.slipGenerated ? (
              <button className="btn btn-primary mt-16" onClick={() => openSlip(data.id)}>View Salary Slip (PDF)</button>
            ) : (
              <div className="text-xs text-muted mt-16">Salary slip will be available once generated by HR.</div>
            )}
          </div>
        </div>

        <div className="card">
          <div className="card-header"><div className="card-title">My Salary History (last 6 months)</div></div>
          <div className="card-body" style={{ padding: 0 }}>
            {history.length === 0 && <EmptyState icon="💰" title="No salary records" />}
            <table className="table">
              <thead>
                <tr><th>Month</th><th>Net Salary</th><th>Status</th><th></th></tr>
              </thead>
              <tbody>
                {history.map((p) => (
                  <tr key={`${p.year}-${p.month}`}>
                    <td>{MONTHS[(p.month || 1) - 1]} {p.year}</td>
                    <td>₹ {Number(p.netSalary).toLocaleString('en-IN')}</td>
                    <td><StatusBadge status={p.status} labels={{ draft: 'Draft', finalized: 'Finalized', paid: 'Paid' }} /></td>
                    <td>
                      {p.slipGenerated && <button className="btn btn-ghost btn-sm" onClick={() => openSlip(p.id)}>Slip</button>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  )
}