export const statements = [
  // ---------- HRCRM users (own auth domain; never touches the other software's `users` table) ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_users (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NULL,
    email VARCHAR(191) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('worker','it','director') NOT NULL DEFAULT 'worker',
    status ENUM('pending_onboarding','active','inactive') NOT NULL DEFAULT 'pending_onboarding',
    name VARCHAR(255) NULL,
    onboardingToken VARCHAR(64) NULL,
    onboardingTokenExpiresAt DATETIME NULL,
    lastLoginAt DATETIME NULL,
    failedLoginAttempts INT NOT NULL DEFAULT 0,
    lockedUntil DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_users_email (email),
    UNIQUE KEY uq_hrcrm_users_employee (employeeId),
    UNIQUE KEY uq_hrcrm_users_onboarding (onboardingToken),
    KEY idx_hrcrm_users_role (role),
    KEY idx_hrcrm_users_status (status),
    CONSTRAINT fk_hrcrm_users_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  `CREATE TABLE IF NOT EXISTS hrcrm_password_reset_tokens (
    id INT NOT NULL AUTO_INCREMENT,
    userId INT NOT NULL,
    tokenHash VARCHAR(64) NOT NULL,
    expiresAt DATETIME NOT NULL,
    usedAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_pwd_tokens_hash (tokenHash),
    KEY idx_hrcrm_pwd_tokens_user (userId),
    CONSTRAINT fk_hrcrm_pwd_tokens_user FOREIGN KEY (userId) REFERENCES hrcrm_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 1: Personal information ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_profile_details (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    fatherName VARCHAR(255) NULL,
    motherName VARCHAR(255) NULL,
    dateOfBirth DATE NULL,
    gender ENUM('male','female','other') NULL,
    bloodGroup VARCHAR(10) NULL,
    maritalStatus ENUM('married','single') NULL,
    nationality VARCHAR(100) NULL,
    aadhaarNumber VARCHAR(20) NULL,
    panNumber VARCHAR(20) NULL,
    passportNumber VARCHAR(30) NULL,
    drivingLicence ENUM('yes','no') NULL,
    uanNumber VARCHAR(30) NULL,
    esicNumber VARCHAR(30) NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_profile_employee (employeeId),
    CONSTRAINT fk_hrcrm_profile_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 2: Contact & family ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_contact_details (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    mobileNumber VARCHAR(20) NULL,
    alternateMobile VARCHAR(20) NULL,
    personalEmail VARCHAR(191) NULL,
    officialEmail VARCHAR(191) NULL,
    currentAddress TEXT NULL,
    permanentAddress TEXT NULL,
    emergencyContactName VARCHAR(255) NULL,
    emergencyRelation VARCHAR(100) NULL,
    emergencyContactNumber VARCHAR(20) NULL,
    emergencyAddress TEXT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_contact_employee (employeeId),
    CONSTRAINT fk_hrcrm_contact_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 3: Education (dynamic rows) ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_education (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    qualification VARCHAR(255) NOT NULL,
    institute VARCHAR(255) NULL,
    year VARCHAR(20) NULL,
    percentage VARCHAR(20) NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_education_employee (employeeId),
    CONSTRAINT fk_hrcrm_education_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 4: Previous employment + bank details ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_employment_details (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    previousCompany VARCHAR(255) NULL,
    previousDesignation VARCHAR(255) NULL,
    experienceYears VARCHAR(20) NULL,
    reasonForLeaving TEXT NULL,
    lastSalary DECIMAL(12,2) NULL,
    bankName VARCHAR(100) NULL,
    branch VARCHAR(100) NULL,
    accountNumber VARCHAR(30) NULL,
    ifscCode VARCHAR(20) NULL,
    upiId VARCHAR(100) NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_employment_employee (employeeId),
    CONSTRAINT fk_hrcrm_employment_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 5: Skills ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_skills (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    category ENUM('it','non_it') NOT NULL,
    skill VARCHAR(100) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_skills (employeeId, category, skill),
    KEY idx_hrcrm_skills_employee (employeeId),
    CONSTRAINT fk_hrcrm_skills_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Profile Section 6: Documents (base64 stored; survives serverless) ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_documents (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    docType VARCHAR(60) NOT NULL,
    category ENUM('personal','educational','employment','company_letters','identity','bank','compliance','other') NOT NULL DEFAULT 'other',
    originalName VARCHAR(255) NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    mimeType VARCHAR(100) NULL,
    size INT NULL,
    content LONGTEXT NULL,
    verificationStatus ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    verifiedById INT NULL,
    verifiedAt DATETIME NULL,
    rejectionReason TEXT NULL,
    remarks TEXT NULL,
    version INT NOT NULL DEFAULT 1,
    uploadedById INT NULL,
    uploadedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_docs_employee (employeeId),
    KEY idx_hrcrm_docs_type (docType),
    KEY idx_hrcrm_docs_status (verificationStatus),
    CONSTRAINT fk_hrcrm_docs_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Two-level employee verification ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_verification (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    profileStatus ENUM('not_started','incomplete','submitted','it_approved','it_rejected','director_approved','director_rejected','fully_verified') NOT NULL DEFAULT 'not_started',
    itStatus ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    itReviewerId INT NULL,
    itReviewedAt DATETIME NULL,
    itRemarks TEXT NULL,
    directorStatus ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    directorReviewerId INT NULL,
    directorReviewedAt DATETIME NULL,
    directorRemarks TEXT NULL,
    submittedAt DATETIME NULL,
    reopenedById INT NULL,
    reopenedAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_verification_employee (employeeId),
    KEY idx_hrcrm_verification_status (profileStatus),
    KEY idx_hrcrm_verification_it (itStatus),
    KEY idx_hrcrm_verification_director (directorStatus),
    CONSTRAINT fk_hrcrm_verification_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  `CREATE TABLE IF NOT EXISTS hrcrm_verification_history (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    action VARCHAR(60) NOT NULL,
    actorId INT NULL,
    actorRole VARCHAR(20) NULL,
    remarks TEXT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_verif_history_employee (employeeId),
    KEY idx_hrcrm_verif_history_action (action),
    CONSTRAINT fk_hrcrm_verif_history_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Leave requests with two-level approval ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_leaves (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    leaveType ENUM('casual','privilege','half_day','wfh') NOT NULL,
    startDate DATE NOT NULL,
    endDate DATE NOT NULL,
    halfDay ENUM('none','first_half','second_half') NOT NULL DEFAULT 'none',
    days DECIMAL(4,1) NOT NULL DEFAULT 1.0,
    reason TEXT NULL,
    comments TEXT NULL,
    supportingDocName VARCHAR(255) NULL,
    supportingDocContent LONGTEXT NULL,
    status ENUM('draft','pending_it','it_approved','it_rejected','pending_director','director_approved','director_rejected','cancelled') NOT NULL DEFAULT 'draft',
    itStatus ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    itReviewedById INT NULL,
    itReviewedAt DATETIME NULL,
    itRemarks TEXT NULL,
    directorStatus ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    directorReviewedById INT NULL,
    directorReviewedAt DATETIME NULL,
    directorRemarks TEXT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_leaves_employee (employeeId),
    KEY idx_hrcrm_leaves_status (status),
    KEY idx_hrcrm_leaves_dates (startDate, endDate),
    CONSTRAINT fk_hrcrm_leaves_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  `CREATE TABLE IF NOT EXISTS hrcrm_leave_balances (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    leaveType ENUM('casual','privilege','half_day','wfh') NOT NULL,
    year INT NOT NULL,
    total DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    used DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_leave_balances (employeeId, leaveType, year),
    CONSTRAINT fk_hrcrm_leave_balances_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Letters ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_letters (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    letterType ENUM('offer','joining','appointment','increment','promotion') NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    pdfContent LONGTEXT NULL,
    version INT NOT NULL DEFAULT 1,
    status ENUM('draft','generated','sent') NOT NULL DEFAULT 'generated',
    generatedById INT NULL,
    generatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sentById INT NULL,
    sentAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_letters_employee (employeeId),
    KEY idx_hrcrm_letters_type (letterType),
    CONSTRAINT fk_hrcrm_letters_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Configurable salary rules ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_salary_config (
    id INT NOT NULL AUTO_INCREMENT,
    cfgKey VARCHAR(100) NOT NULL,
    cfgValue TEXT NULL,
    updatedBy INT NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_salary_config_key (cfgKey)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Payroll records (attendance-derived) ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_payrolls (
    id INT NOT NULL AUTO_INCREMENT,
    employeeId INT NOT NULL,
    month INT NOT NULL,
    year INT NOT NULL,
    presentDays DECIMAL(5,1) NOT NULL DEFAULT 0,
    absentDays DECIMAL(5,1) NOT NULL DEFAULT 0,
    leaveDays DECIMAL(5,1) NOT NULL DEFAULT 0,
    halfDays DECIMAL(5,1) NOT NULL DEFAULT 0,
    wfhDays DECIMAL(5,1) NOT NULL DEFAULT 0,
    lateDays INT NOT NULL DEFAULT 0,
    overtimeMinutes INT NOT NULL DEFAULT 0,
    totalHours DECIMAL(6,2) NOT NULL DEFAULT 0,
    basicSalary DECIMAL(12,2) NOT NULL DEFAULT 0,
    hra DECIMAL(12,2) NOT NULL DEFAULT 0,
    da DECIMAL(12,2) NOT NULL DEFAULT 0,
    allowances DECIMAL(12,2) NOT NULL DEFAULT 0,
    overtimeAmount DECIMAL(12,2) NOT NULL DEFAULT 0,
    grossSalary DECIMAL(12,2) NOT NULL DEFAULT 0,
    absentDeduction DECIMAL(12,2) NOT NULL DEFAULT 0,
    lateDeduction DECIMAL(12,2) NOT NULL DEFAULT 0,
    pf DECIMAL(12,2) NOT NULL DEFAULT 0,
    esic DECIMAL(12,2) NOT NULL DEFAULT 0,
    professionalTax DECIMAL(12,2) NOT NULL DEFAULT 0,
    otherDeductions DECIMAL(12,2) NOT NULL DEFAULT 0,
    totalDeductions DECIMAL(12,2) NOT NULL DEFAULT 0,
    netSalary DECIMAL(12,2) NOT NULL DEFAULT 0,
    status ENUM('draft','finalized','paid') NOT NULL DEFAULT 'draft',
    notes TEXT NULL,
    calculatedById INT NULL,
    calculatedAt DATETIME NULL,
    finalizedById INT NULL,
    finalizedAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_payrolls (employeeId, month, year),
    KEY idx_hrcrm_payrolls_month (month, year),
    KEY idx_hrcrm_payrolls_status (status),
    CONSTRAINT fk_hrcrm_payrolls_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  `CREATE TABLE IF NOT EXISTS hrcrm_salary_slips (
    id INT NOT NULL AUTO_INCREMENT,
    payrollId INT NOT NULL,
    employeeId INT NOT NULL,
    pdfContent LONGTEXT NULL,
    generatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sentById INT NULL,
    sentAt DATETIME NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_salary_slips_payroll (payrollId),
    KEY idx_hrcrm_salary_slips_employee (employeeId),
    CONSTRAINT fk_hrcrm_salary_slips_payroll FOREIGN KEY (payrollId) REFERENCES hrcrm_payrolls(id) ON DELETE CASCADE,
    CONSTRAINT fk_hrcrm_salary_slips_employee FOREIGN KEY (employeeId) REFERENCES employees(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- Email logs ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_email_logs (
    id INT NOT NULL AUTO_INCREMENT,
    recipient VARCHAR(191) NOT NULL,
    senderEmail VARCHAR(191) NULL,
    senderName VARCHAR(191) NULL,
    subject VARCHAR(255) NOT NULL,
    category VARCHAR(60) NULL,
    status ENUM('sent','failed') NOT NULL DEFAULT 'sent',
    error TEXT NULL,
    relatedEntity VARCHAR(60) NULL,
    relatedId INT NULL,
    sentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_email_logs_recipient (recipient),
    KEY idx_hrcrm_email_logs_status (status),
    KEY idx_hrcrm_email_logs_sent (sentAt)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- In-app notifications ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_notifications (
    id INT NOT NULL AUTO_INCREMENT,
    userId INT NULL,
    title VARCHAR(191) NOT NULL,
    message TEXT NOT NULL,
    type ENUM('info','success','warning','error','email','leave','payroll','document','verification','letter') NOT NULL DEFAULT 'info',
    relatedEntity VARCHAR(60) NULL,
    relatedId INT NULL,
    isRead TINYINT(1) NOT NULL DEFAULT 0,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hrcrm_notifications_user (userId),
    KEY idx_hrcrm_notifications_read (isRead),
    KEY idx_hrcrm_notifications_created (createdAt),
    CONSTRAINT fk_hrcrm_notifications_user FOREIGN KEY (userId) REFERENCES hrcrm_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,

  // ---------- HRCRM settings ----------
  `CREATE TABLE IF NOT EXISTS hrcrm_settings (
    id INT NOT NULL AUTO_INCREMENT,
    settingKey VARCHAR(100) NOT NULL,
    settingValue TEXT NULL,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_hrcrm_settings_key (settingKey)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
];